apiVersion: v1
kind: PersistentVolume
metadata:
  name: hellz-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
#    path: /run/desktop/mnt/host/c/repo/Kubernetes/data
#    path: /var/lib/docker/volumes/hellz-volume/_data
    path: /run/desktop/mnt/host/c/Users/ISAC/data
    type: DirectoryOrCreate